# This workflow runs the configured unit tests after installing tSQLt on a SQL Server instance inside a Docker container!

name: Unit testing runner

#---------- 1. Definition of activation events

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

#---------- 2. Creating a Docker container from a SQL Server image on Linux

jobs:

  windows-auth-tsqlt:
    
    name: Installing tSQLt framework and running unit tests
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: chriseaton/adventureworks:latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: 3uuiCaKxfbForrK

    steps: